import { NodeType } from '../domain/models';

export interface PropertyField {
  key:          string;
  label:        string;
  type:         'text' | 'number' | 'select' | 'boolean' | 'textarea' | 'preset';
  placeholder?: string;
  options?:     string[];
  unit?:        string;
  /** HTML5 pattern for native browser validation (e.g. IPv4 format hint). */
  pattern?:     string;
}

export const NODE_SCHEMAS: Record<NodeType, PropertyField[]> = {
  server: [
    { key: 'ip',               label: 'Adresse IP',          type: 'text',     placeholder: '192.168.1.10', pattern: '^(\\d{1,3}\\.){3}\\d{1,3}$' },
    { key: 'hostname',         label: 'Hostname',            type: 'text',     placeholder: 'srv-web-01' },
    { key: 'os',               label: 'Système d\'exploitation', type: 'select', options: ['Ubuntu 22.04', 'Ubuntu 20.04', 'Debian 12', 'Debian 11', 'RHEL 9', 'CentOS Stream 9', 'Windows Server 2022', 'Windows Server 2019', 'Alpine Linux'] },
    { key: 'role',             label: 'Rôle',                type: 'text',     placeholder: 'web, app, backup, monitoring...' },
    { key: 'zone',             label: 'Zone réseau',         type: 'text',     placeholder: 'DMZ, APP, DATA, CORE...' },
    { key: 'cpu',              label: 'CPU (vCores)',  type: 'preset', options: ['1', '2', '4', '8', '16', '32'] },
    { key: 'ram',              label: 'RAM (Go)',      type: 'preset', options: ['1', '2', '4', '8', '16', '32', '64', '128'] },
    { key: 'storage',          label: 'Stockage (Go)', type: 'preset', options: ['20', '50', '100', '200', '500', '1000'] },
    { key: 'template_vm_id',   label: 'Template VM ID (Proxmox)', type: 'number', placeholder: '9000 — remplace le template global' },
    { key: 'notes',            label: 'Notes',               type: 'textarea', placeholder: 'Informations complémentaires...' },
  ],
  database: [
    { key: 'ip',                 label: 'Adresse IP',          type: 'text', pattern: '^(\\d{1,3}\\.){3}\\d{1,3}$' },
    { key: 'engine',             label: 'Moteur',              type: 'select', options: ['PostgreSQL 16', 'PostgreSQL 15', 'MySQL 8.0', 'MariaDB 10.11', 'MongoDB 7', 'Redis 7', 'SQL Server 2022', 'Oracle 21c', 'SQLite', 'Elasticsearch 8'] },
    { key: 'version',            label: 'Version',             type: 'text' },
    { key: 'port',               label: 'Port',                type: 'number',   placeholder: '5432' },
    { key: 'publish_port',       label: 'Exposer le port hôte', type: 'boolean' },
    { key: 'host_port',          label: 'Port hôte',           type: 'number',   placeholder: '5432' },
    { key: 'db_name',            label: 'Nom base',            type: 'text',     placeholder: 'app' },
    { key: 'db_user',            label: 'Utilisateur',         type: 'text',     placeholder: 'app' },
    { key: 'db_password',        label: 'Mot de passe',        type: 'text',     placeholder: 'app_password' },
    { key: 'zone',               label: 'Zone réseau',         type: 'text' },
    { key: 'role',               label: 'Rôle',                type: 'select',   options: ['primary', 'replica', 'standalone', 'arbiter', 'shard'] },
    { key: 'backup_enabled',     label: 'Backup activé',       type: 'boolean' },
    { key: 'notes',              label: 'Notes',               type: 'textarea' },
  ],
  application: [
    { key: 'github_repo',       label: 'Repository GitHub',   type: 'text',     placeholder: 'https://github.com/org/repo' },
    { key: 'github_ref',        label: 'Branche / tag / commit', type: 'text',  placeholder: 'main' },
    { key: 'dockerfile_path',   label: 'Chemin Dockerfile',   type: 'text',     placeholder: 'Dockerfile' },
    { key: 'docker_port',       label: 'Docker port',         type: 'number',   placeholder: '3000' },
    { key: 'expose_port',       label: 'Expose port',         type: 'number',   placeholder: '6000' },
    { key: 'command',           label: 'Commande (optionnel)', type: 'text',    placeholder: 'npm run start' },
    { key: 'cpu',               label: 'CPU (vCores)',  type: 'preset', options: ['1', '2', '4', '8', '16'] },
    { key: 'ram',               label: 'RAM (Go)',      type: 'preset', options: ['1', '2', '4', '8', '16', '32'] },
    { key: 'disk',              label: 'Disque (Go)',   type: 'preset', options: ['10', '20', '40', '80', '100'] },
    { key: 'template_vm_id',    label: 'Template VM ID (Proxmox)', type: 'number', placeholder: '9000 — remplace le template global' },
    { key: 'notes',             label: 'Notes',               type: 'textarea', placeholder: 'Si le repo n\'a pas de Dockerfile, définir image/command en propriétés personnalisées.' },
  ],
  api: [
    { key: 'url',                label: 'URL de base',         type: 'text',     placeholder: 'https://api.corp.local' },
    { key: 'protocol',           label: 'Protocole',           type: 'select',   options: ['HTTP', 'HTTPS', 'gRPC', 'WebSocket', 'GraphQL'] },
    { key: 'auth_type',          label: 'Authentification',    type: 'select',   options: ['None', 'JWT', 'API Key', 'OAuth2', 'mTLS', 'Basic Auth'] },
    { key: 'version',            label: 'Version API',         type: 'text',     placeholder: 'v1' },
    { key: 'port',               label: 'Port',                type: 'number' },
    { key: 'publish_port',       label: 'Exposer le port hôte', type: 'boolean' },
    { key: 'host_port',          label: 'Port hôte',           type: 'number',   placeholder: '8080' },
    { key: 'zone',               label: 'Zone',                type: 'text' },
    { key: 'rate_limit',         label: 'Rate limit (req/s)',  type: 'number' },
    { key: 'notes',              label: 'Notes',               type: 'textarea' },
  ],
  firewall: [
    { key: 'ip',              label: 'Adresse IP',   type: 'text', pattern: '^(\\d{1,3}\\.){3}\\d{1,3}$' },
    { key: 'hostname',        label: 'Hostname',     type: 'text',   placeholder: 'fw-01' },
    { key: 'vendor',          label: 'Constructeur', type: 'select', options: ['pfSense', 'OPNsense', 'Fortinet', 'Palo Alto', 'Cisco ASA', 'Juniper SRX', 'Check Point', 'Sophos', 'Azure Firewall'] },
    { key: 'model',           label: 'Modèle',       type: 'text',   placeholder: 'FortiGate 100F' },
    { key: 'cpu',             label: 'CPU (vCores)', type: 'preset', options: ['1', '2', '4', '8'] },
    { key: 'ram',             label: 'RAM (Go)',     type: 'preset', options: ['1', '2', '4', '8', '16'] },
    { key: 'disk',            label: 'Disque (Go)',  type: 'preset', options: ['10', '20', '40', '80'] },
    { key: 'template_vm_id',  label: 'Template VM ID (Proxmox)', type: 'number', placeholder: '9000' },
    { key: 'zone',            label: 'Zone',         type: 'text' },
    { key: 'firmware',        label: 'Firmware',     type: 'text' },
    { key: 'ha_mode',         label: 'Mode HA',      type: 'select', options: ['standalone', 'active-passive', 'active-active'] },
    { key: 'rules_count',     label: 'Nb règles',    type: 'number' },
    { key: 'notes',           label: 'Notes',        type: 'textarea' },
  ],
  network: [
    { key: 'subnet',             label: 'Sous-réseau',         type: 'text',     placeholder: '10.0.0.0/24' },
    { key: 'cidr',               label: 'CIDR',                type: 'text',     placeholder: '10.0.0.0/16' },
    { key: 'vlan',               label: 'VLAN ID',             type: 'number' },
    { key: 'zone',               label: 'Zone',                type: 'text' },
    { key: 'gateway',            label: 'Passerelle',          type: 'text' },
    { key: 'dns',                label: 'DNS',                 type: 'text' },
    { key: 'notes',              label: 'Notes',               type: 'textarea' },
  ],
  router: [
    { key: 'ip',                 label: 'Adresse IP',          type: 'text', pattern: '^(\\d{1,3}\\.){3}\\d{1,3}$' },
    { key: 'vendor',             label: 'Constructeur',        type: 'select',   options: ['Cisco', 'Juniper', 'Mikrotik', 'Huawei', 'Aruba', 'pfSense', 'Azure'] },
    { key: 'model',              label: 'Modèle',              type: 'text' },
    { key: 'interfaces_count',   label: 'Nb interfaces',       type: 'number' },
    { key: 'zone',               label: 'Zone',                type: 'text' },
    { key: 'protocol',           label: 'Protocole routage',   type: 'select',   options: ['BGP', 'OSPF', 'EIGRP', 'RIP', 'Static'] },
    { key: 'notes',              label: 'Notes',               type: 'textarea' },
  ],
  switch: [
    { key: 'ip',                 label: 'Adresse IP mgmt',     type: 'text', pattern: '^(\\d{1,3}\\.){3}\\d{1,3}$' },
    { key: 'vendor',             label: 'Constructeur',        type: 'select',   options: ['Cisco', 'HP / Aruba', 'Juniper', 'Dell', 'Huawei', 'Netgear', 'Ubiquiti'] },
    { key: 'model',              label: 'Modèle',              type: 'text',     placeholder: 'Catalyst 9300' },
    { key: 'port_count',         label: 'Nb ports',            type: 'number',   placeholder: '48' },
    { key: 'vlans',              label: 'VLANs (virgule)',     type: 'text',     placeholder: '10,20,30,40' },
    { key: 'zone',               label: 'Zone',                type: 'text' },
    { key: 'poe',                label: 'PoE',                 type: 'boolean' },
    { key: 'notes',              label: 'Notes',               type: 'textarea' },
  ],
  cloud: [
    { key: 'provider',           label: 'Fournisseur',         type: 'select',   options: ['Azure', 'AWS', 'GCP', 'OVH', 'Scaleway', 'Hetzner', 'DigitalOcean'] },
    { key: 'service',            label: 'Service',             type: 'text',     placeholder: 'Azure Kubernetes Service, S3, Cloud Run...' },
    { key: 'region',             label: 'Région',              type: 'text',     placeholder: 'West Europe, eu-west-1...' },
    { key: 'zone',               label: 'Zone',                type: 'text' },
    { key: 'account_id',         label: 'Account / Sub ID',    type: 'text' },
    { key: 'notes',              label: 'Notes',               type: 'textarea' },
  ],
  service: [
    { key: 'url',                label: 'URL',                 type: 'text' },
    { key: 'protocol',           label: 'Protocole',           type: 'select',   options: ['HTTP', 'HTTPS', 'gRPC', 'WebSocket', 'AMQP', 'MQTT', 'Kafka', 'Redis', 'SMTP'] },
    { key: 'port',               label: 'Port',                type: 'number' },
    { key: 'zone',               label: 'Zone',                type: 'text' },
    { key: 'notes',              label: 'Notes',               type: 'textarea' },
  ],
  workstation: [
    { key: 'ip',             label: 'Adresse IP',   type: 'text', pattern: '^(\\d{1,3}\\.){3}\\d{1,3}$' },
    { key: 'hostname',       label: 'Hostname',     type: 'text' },
    { key: 'os',             label: 'Système',      type: 'select', options: ['Windows 11', 'Windows 10', 'macOS Sonoma', 'Ubuntu Desktop', 'Fedora', 'Arch Linux'] },
    { key: 'cpu',            label: 'CPU (vCores)', type: 'preset', options: ['1', '2', '4', '8'] },
    { key: 'ram',            label: 'RAM (Go)',     type: 'preset', options: ['2', '4', '8', '16', '32'] },
    { key: 'disk',           label: 'Disque (Go)',  type: 'preset', options: ['40', '80', '100', '200', '500'] },
    { key: 'template_vm_id', label: 'Template VM ID (Proxmox)', type: 'number', placeholder: '9000 — remplace le template global' },
    { key: 'user_name',      label: 'Utilisateur',  type: 'text' },
    { key: 'zone',           label: 'Zone',         type: 'text' },
    { key: 'notes',          label: 'Notes',        type: 'textarea' },
  ],
  user: [
    { key: 'email',              label: 'Email',               type: 'text' },
    { key: 'role',               label: 'Rôle',                type: 'text',     placeholder: 'Admin, DevOps, DBA...' },
    { key: 'department',         label: 'Département',         type: 'text' },
    { key: 'phone',              label: 'Téléphone',           type: 'text' },
    { key: 'notes',              label: 'Notes',               type: 'textarea' },
  ],
  vm: [
    { key: 'ip',              label: 'Adresse IP',          type: 'text',    placeholder: '192.168.1.10', pattern: '^(\\d{1,3}\\.){3}\\d{1,3}$' },
    { key: 'hostname',        label: 'Hostname',             type: 'text',    placeholder: 'vm-web-01' },
    { key: 'os',              label: 'Système d\'exploitation', type: 'select', options: ['Ubuntu 22.04', 'Ubuntu 20.04', 'Debian 12', 'Alpine Linux', 'Windows Server 2022', 'RHEL 9', 'CentOS Stream 9'] },
    { key: 'cpu',             label: 'CPU (vCores)',  type: 'preset', options: ['1', '2', '4', '8', '16', '32'] },
    { key: 'ram',             label: 'RAM (Go)',      type: 'preset', options: ['1', '2', '4', '8', '16', '32', '64'] },
    { key: 'disk',            label: 'Disque (Go)',   type: 'preset', options: ['10', '20', '40', '80', '100', '200', '500'] },
    { key: 'template_vm_id',  label: 'Template VM ID (Proxmox)', type: 'number', placeholder: '9000 — remplace le template global' },
    { key: 'hypervisor',      label: 'Hyperviseur',          type: 'select',  options: ['Proxmox VE', 'VMware ESXi', 'Hyper-V', 'KVM', 'VirtualBox', 'Xen'] },
    { key: 'vlan',            label: 'VLAN',                 type: 'number' },
    { key: 'zone',            label: 'Zone réseau',          type: 'text',    placeholder: 'DMZ, APP, DATA...' },
    { key: 'notes',           label: 'Notes',                type: 'textarea' },
  ],
  container: [
    { key: 'image',      label: 'Image',                type: 'text',    placeholder: 'nginx:alpine, ubuntu:22.04...' },
    { key: 'ip',         label: 'Adresse IP',           type: 'text',    placeholder: '192.168.1.20 (vide = DHCP)', pattern: '^(\\d{1,3}\\.){3}\\d{1,3}$' },
    { key: 'cpu', label: 'CPU (cœurs)', type: 'preset', options: ['0.5', '1', '2', '4', '8'] },
    { key: 'ram', label: 'RAM (Mo)',    type: 'preset', options: ['256', '512', '1024', '2048', '4096', '8192'] },
    { key: 'port',       label: 'Port exposé',          type: 'number',  placeholder: '80' },
    { key: 'hostname',   label: 'Hostname',             type: 'text',    placeholder: 'ct-nginx-01' },
    { key: 'runtime',    label: 'Runtime',              type: 'select',  options: ['Docker', 'Podman', 'Proxmox LXC', 'containerd'] },
    { key: 'volumes',    label: 'Volumes (virgule)',    type: 'text',    placeholder: '/data:/app/data,/logs:/var/log' },
    { key: 'env',        label: 'Variables env',        type: 'textarea', placeholder: 'KEY=val\nKEY2=val2' },
    { key: 'zone',       label: 'Zone réseau',          type: 'text' },
    { key: 'notes',      label: 'Notes',                type: 'textarea' },
  ],
  unknown: [
    { key: 'notes', label: 'Notes', type: 'textarea' },
  ],
};
